### ISSUE TITLE
Can't connect to any devices. IOE: Operation not permitted

### ISSUE THREAD

**Issue by ilya-epifanov** [syncthing/syncthing-lite#143]
LocalDiscoveryHandler.sendAnnounceMessage
LocalDiscoveryUtil.sendAnnounceMessage
interface: name:wlan0 (wlan0)
address: /192.168.178.18/24 [/192.168.178.255]
broadcast address: /192.168.178.255

net.syncthing.a.c.c.a: java.io.IOException: Operation not permitted
	at net.syncthing.a.d.a.h.a(LocalDiscoveryUtil.kt:134)
	at net.syncthing.a.d.a.e$a.c_(LocalDiscoveryHandler.kt:39)
	at a.c.b.a.a.b(ContinuationImpl.kt:32)
	at kotlinx.coroutines.az$a.a(Dispatched.kt:235)
	at kotlinx.coroutines.aw.run(Dispatched.kt:81)
	at kotlinx.coroutines.c.i.run(Tasks.kt:94)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:732)
Caused by: java.io.IOException: Operation not permitted
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:696)
	at net.syncthing.a.d.a.h.a(LocalDiscoveryUtil.kt:127)
	... 8 more

**Comment by zoj613** [comment]
Same here. It doesnt work at all.

**Comment by l-jonas** [comment]
Anything specific? Device model? Android version?

**Comment by ilya-epifanov** [comment]
Happens on:
Pixel 4, Android 10
Samsung Galaxy S8, Android 9 (?)

**Comment by ilya-epifanov** [comment]
It also seems to be interfering with global discovery, as it happens very very slowly.
