### ISSUE TITLE
Error pop-up without using app

### ISSUE THREAD

**Issue by Newar417** [syncthing/syncthing-lite#145]
Today I had an error message pop-up, even though I have not used the app in a good while. This is on a stock Motorola G4plus. All the latest versions, Syncthing Lite is from FDroid on both.

This is the error as reported from the app error reporter function:

`LocalDiscoveryHandler.sendAnnounceMessage
LocalDiscoveryUtil.sendAnnounceMessage
interface: name:wlan0 (wlan0)
address: /192.168.1.115/24 [/192.168.1.255]
broadcast address: /192.168.1.255

net.syncthing.a.c.c.a: java.io.IOException: Operation not permitted
	at net.syncthing.a.d.a.h.a(LocalDiscoveryUtil.kt:134)
	at net.syncthing.a.d.a.e$a.c_(LocalDiscoveryHandler.kt:39)
	at a.c.b.a.a.b(ContinuationImpl.kt:32)
	at kotlinx.coroutines.az$a.a(Dispatched.kt:235)
	at kotlinx.coroutines.aw.run(Dispatched.kt:81)
	at kotlinx.coroutines.c.i.run(Tasks.kt:94)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:732)
Caused by: java.io.IOException: Operation not permitted
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:699)
	at net.syncthing.a.d.a.h.a(LocalDiscoveryUtil.kt:127)
	... 8 more
`

**Comment by zoj613** [comment]
Same thing happens on my phone . I randomly see toats on the screen saying 'something wrong happened with Syncthing Lite....'
