### ISSUE TITLE
Unable to open Syncthing files from other apps

### ISSUE THREAD

**Issue by hackel** [syncthing/syncthing-lite#32]
When I try to browse the "Syncthing Lite" file provider when choosing files from other apps using the standard file chooser, I get "Files has stopped" with a NullPointerException.

Here is a logcat that shows a stacktrace of Files crashing (Sorry, I filtered this as best I could):
```logcat
03-06 21:15:02.440   964  2102 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.documentsui/.LauncherActivity bnds=[540,616][698,797] (has extras)} from uid 10140
03-06 21:15:02.441   706  2967 I ACDB-LOADER: ACDB AFE returned = -19
03-06 21:15:02.496   964  3154 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@cef34c7
03-06 21:15:02.505   964  3153 I ActivityManager: START u0 {dat=//com.android.documentsui.launchControl flg=0x10380000 cmp=com.android.documentsui/.files.FilesActivity (has extras)} from uid 10013
03-06 21:15:02.566 24644 24644 W ActionModeController: Tried to finish a null action mode.
03-06 21:15:02.730   964  1063 I ActivityManager: Displayed com.android.documentsui/.files.FilesActivity: +176ms (total +224ms)
03-06 21:15:02.942  3718  3718 W JNIHelp : Discarding pending exception (java.io.IOException: Try again) to throw java/io/IOException
03-06 21:15:03.024 18625 18625 I StreamRenderer: cleanUpRendererScope(nowcards--6733982134659492570)
03-06 21:15:03.040 18625 25262 I PBSessionCacheImpl: Deleted sessionId[101788748966383] from persistence.
03-06 21:15:03.069 18625 18625 W SearchService: Abort, client detached.
03-06 21:15:03.086 18625 18625 I StreamController: cleanUpControllerScope(nowcards--6733982134659492570)
03-06 21:15:03.942  3718  3718 W JNIHelp : Discarding pending exception (java.io.IOException: Try again) to throw java/io/IOException
03-06 21:15:04.460 17182 17182 W Notification: Use of stream types is deprecated for operations other than volume control
03-06 21:15:04.460 17182 17182 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-06 21:15:04.573   964  3154 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@e41f66
03-06 21:15:04.574  3538 25323 W DropBoxEntryAddedChimeraService: Could not connect to Google API Client, giving up...
03-06 21:15:04.580   964  3154 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@196a2a7
03-06 21:15:04.581  3538 25323 W DropBoxEntryAddedChimeraService: Could not connect to Google API Client, giving up...
03-06 21:15:05.384 24644 24644 W ActionModeController: Tried to finish a null action mode.
03-06 21:15:05.395 20716 20727 D SyncthingProvider: queryDocument(sync:, null)
03-06 21:15:05.399 20716 20727 I IndexBrowser: navigate to path = ''
03-06 21:15:05.403 20716 25325 I IndexBrowser: folder preload BEGIN for folder = 'sync' path = ''
03-06 21:15:05.429 20716 25325 I IndexBrowser: folder preload END for folder = 'sync' path = ''
03-06 21:15:05.429 20716 25325 I IndexBrowser: cache ready, notify listeners
03-06 21:15:05.448 20716 20728 D SyncthingProvider: queryChildDocuments(sync:, null, _display_name ASC)
03-06 21:15:05.449 20716 20728 I IndexBrowser: navigate to path = ''
03-06 21:15:05.450 20716 25327 I IndexBrowser: folder preload BEGIN for folder = 'sync' path = ''
03-06 21:15:05.456 20716 25327 I IndexBrowser: folder preload END for folder = 'sync' path = ''
03-06 21:15:05.457 20716 25327 I IndexBrowser: cache ready, notify listeners
03-06 21:15:05.458 20716 20727 D SyncthingProvider: queryChildDocuments(sync:, null, _display_name ASC)
03-06 21:15:05.461 20716 20727 I IndexBrowser: navigate to path = ''
03-06 21:15:05.468 20716 25328 I IndexBrowser: folder preload BEGIN for folder = 'sync' path = ''
03-06 21:15:05.472 20716 25328 I IndexBrowser: folder preload END for folder = 'sync' path = ''
03-06 21:15:05.472 20716 25328 I IndexBrowser: cache ready, notify listeners
03-06 21:15:05.518 24644 24644 D AndroidRuntime: Shutting down VM
03-06 21:15:05.519 24644 24644 E AndroidRuntime: FATAL EXCEPTION: main
03-06 21:15:05.519 24644 24644 E AndroidRuntime: Process: com.android.documentsui, PID: 24644
03-06 21:15:05.519 24644 24644 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at com.android.documentsui.base.MimeTypes.splitMimeType(MimeTypes.java:40)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at com.android.documentsui.FileTypeMap.lookup(FileTypeMap.java:118)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at com.android.documentsui.FileTypeMap.lookup(FileTypeMap.java:103)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at com.android.documentsui.dirlist.ListDocumentHolder.bind(ListDocumentHolder.java:203)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at com.android.documentsui.dirlist.ModelBackedDocumentsAdapter.onBindViewHolder(ModelBackedDocumentsAdapter.java:124)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at com.android.documentsui.dirlist.ModelBackedDocumentsAdapter.onBindViewHolder(ModelBackedDocumentsAdapter.java:116)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at com.android.documentsui.dirlist.ModelBackedDocumentsAdapter.onBindViewHolder(ModelBackedDocumentsAdapter.java:110)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at com.android.documentsui.dirlist.DirectoryAddonsAdapter.onBindViewHolder(DirectoryAddonsAdapter.java:130)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at com.android.documentsui.dirlist.DirectoryAddonsAdapter.onBindViewHolder(DirectoryAddonsAdapter.java:117)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1712)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4832)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:655)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
03-06 21:15:05.519 24644 24644 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
03-06 21:15:05.523   964  3153 W ActivityManager:   Force finishing activity com.android.documentsui/.files.FilesActivity
03-06 21:15:05.533   964  1033 I ActivityManager: Showing crash dialog for package com.android.documentsui u0
03-06 21:15:05.549  3718  3718 W JNIHelp : Discarding pending exception (java.io.IOException: Try again) to throw java/io/IOException
03-06 21:15:05.558   964  3154 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@d38351c
03-06 21:15:05.559  3538 25330 W DropBoxEntryAddedChimeraService: Could not connect to Google API Client, giving up...
03-06 21:15:06.027   964  1029 W ActivityManager: Activity pause timeout for ActivityRecord{c119c92 u0 com.android.documentsui/.files.FilesActivity t39480 f}
03-06 21:15:06.113   964 15004 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@e9dd249
03-06 21:15:06.247 18625 18625 W SessionLifecycleManager: Handover failed. Creating new session controller.
03-06 21:15:06.265 18625 18625 I OptInState: There is a new client and it does not support opt-in. Dropping request.
03-06 21:15:06.280 18625 18625 I StreamController: registerScope: nowcards--6733982134659492570
03-06 21:15:06.315 18625 18625 I StreamRenderer: maybeRegisterNowCardsScope(nowcards--6733982134659492570, com.google.android.sidekick.shared.remoteapi.CardRenderingContext@aea1089)
03-06 21:15:06.427 11964 11964 W Notification: Use of stream types is deprecated for operations other than volume control
03-06 21:15:06.427 11964 11964 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-06 21:15:06.468   964 15008 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@ace146b
03-06 21:15:06.469  3538 25335 W DropBoxEntryAddedChimeraService: Could not connect to Google API Client, giving up...
03-06 21:15:06.472   964  3150 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@9b97bc8
03-06 21:15:06.473  3538 25335 W DropBoxEntryAddedChimeraService: Could not connect to Google API Client, giving up...
03-06 21:15:06.502  2968  4208 I Places  : ?: PlacesBleScanner stop()
03-06 21:15:06.514  2968  4208 I PlaceInferenceEngine: [anon] Changed inference mode: 105
03-06 21:15:06.549  3718  3718 W JNIHelp : Discarding pending exception (java.io.IOException: Try again) to throw java/io/IOException
03-06 21:15:06.579 17182 17182 W Notification: Use of stream types is deprecated for operations other than volume control
03-06 21:15:06.579 17182 17182 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-06 21:15:07.494   964  3153 W ActivityManager:   Force finishing activity com.android.documentsui/.files.FilesActivity
03-06 21:15:07.535   964  3153 I ActivityManager: Killing 24644:com.android.documentsui/u0a13 (adj 900): crash
03-06 21:15:07.539   964  1033 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
03-06 21:15:07.540   964  1033 W ViewRootImpl[documentsui]: Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=316.0, y[0]=623.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=1, eventTime=209730257, downTime=209730232, deviceId=8, source=0x1002 }
03-06 21:15:07.540   964  1033 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
03-06 21:15:07.549  3718  3718 W JNIHelp : Discarding pending exception (java.io.IOException: Try again) to throw java/io/IOException
03-06 21:15:07.575   964  1063 W ActivityManager: setHasOverlayUi called on unknown pid: 24644
03-06 21:15:07.636   964  1366 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
03-06 21:15:08.750 17182 17182 W Notification: Use of stream types is deprecated for operations other than volume control
03-06 21:15:08.750 17182 17182 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-06 21:15:09.159  3718  3718 W JNIHelp : Discarding pending exception (java.io.IOException: Try again) to throw java/io/IOException
03-06 21:15:10.159  3718  3718 W JNIHelp : Discarding pending exception (java.io.IOException: Try again) to throw java/io/IOException
03-06 21:15:10.896 17182 17182 W Notification: Use of stream types is deprecated for operations other than volume control
03-06 21:15:10.896 17182 17182 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-06 21:15:11.159  3718  3718 W JNIHelp : Discarding pending exception (java.io.IOException: Try again) to throw java/io/IOException
```

Hopefully some of this is helpful in figuring out what is going on.  I'm running the latest Android 8.1.  I've tested this with Google Inbox, Keepass2Android, and the system Downloads app.  The crash is always the same.  Also note that the device is paired correctly and I am able to browse my shared folder from within the app itself.

**Comment by l-jonas** [comment]
The App you use is unrelated as it's always the system dialog. Which Android 8.1 are you using (Google, Samsung, Huawei, ...)?

**Comment by Nutomic** [comment]
@hackel Please reopen when you have new info.
