### ISSUE TITLE
highly unreliable on lineageos

### ISSUE THREAD

**Issue by krodelabestiole** [syncthing/syncthing-lite#35]
hello

I've tried **syncthing-lite 0.2.1** on two different devices both running lineageos 14.1 (based on android 7.1.2) with or without MicroG (I tried first with vanilla lineageos, then flashed _lineageos for microg_)

and I had always had the same results : syncthing-lite crashes when I try to add a new device (at least at first attempt, then eventually it works), then it crashes during scan when it get any new shared directory (one crash for each directory), but launching it again successfully shows the new directory it got.

But then it can't get the indexes for the biggest directories.

And then it never downloads any file (stays blocked at zero percent then fails). About that I suspect a permission issue, since it has never required for autorisation to access my files or sdcard. App Infos in settings -> Applications -> syncthing-lite shows : no autorisation required.

and it also randomly (at least to me) crashes at any moment.

here is info I get in catlog while trying to download a file :
```
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) at java.lang.Thread.run(Thread.java:761) 2018-03-21 03:22:37,ERROR,ExecutorService,Syncthing Lite,java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30035ms.
```

and other errors I can get :
```
2018-03-21 03:25:11,ERROR,ExecutorService,Unknown,org.h2.jdbc.JdbcSQLException: The database has been closed [90098-196]
at org.h2.engine.Session.getTransaction(Session.java:1636)
at org.h2.engine.Session.getStatementSavepoint(Session.java:1646)
at org.h2.engine.Session.setSavepoint(Session.java:825)
at org.h2.command.Command.executeUpdate(Command.java:254)
at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:164)
at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:150)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
at net.syncthing.java.repository.repo.SqlRepository.updateFileInfo(SqlRepository.kt:356)
at net.syncthing.java.bep.IndexHandler.addRecord(IndexHandler.kt:215)
at net.syncthing.java.bep.IndexHandler.pushRecord(IndexHandler.kt:167)
at net.syncthing.java.bep.IndexHandler$IndexMessageProcessor$ProcessingRunnable.doHandleIndexMessageReceivedEvent(IndexHandler.kt:403)
at net.syncthing.java.bep.IndexHandler$IndexMessageProcessor$processBg$1.runProcess(IndexHandler.kt:326)
at net.syncthing.java.bep.IndexHandler$IndexMessageProcessor$ProcessingRunnable.run(IndexHandler.kt:353)
at net.syncthing.java.core.utils.ExecutorUtilsKt$submitLogging$1.invoke(ExecutorUtils.kt:31)
at net.syncthing.java.core.utils.ExecutorUtilsKt$submitLogging$1.invoke(ExecutorUtils.kt)
at net.syncthing.java.core.utils.ExecutorUtilsKt$submitLogging$2.call(ExecutorUtils.kt:40)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by krodelabestiole** [comment]
same problems on lineageos 15.1

**Comment by l-jonas** [comment]
Which build of the App are you using?

**Comment by Nutomic** [comment]
Please open a new issue with logs if you can reproduce this with the latest version.

**Comment by krodelabestiole** [comment]
> Which build of the App are you using (Google Play, F-Droid or self built)?

That was F-Droid... (sorry for the delay)
I will try again with the latest version ASAP
