### ISSUE TITLE
unable to retrieve cluster config from peer

### ISSUE THREAD

**Issue by l-jonas** [syncthing/syncthing-lite#45]
Interestingly, it only occurred for me when using an relay server. Syncthing Lite interprets this as not connected, while the log at the syncthing server says that the device connected

```
09-16 15:22:49.334 1453-1495/net.syncthing.lite W/SyncthingClient: error connecting to device = DeviceAddress(deviceId=removed, instanceId=null, address=relay://removed, producer=UNKNOWN, score=2084, lastModified=Sun Sep 16 15:22:16 GMT+02:00 2018)
    java.io.IOException: unable to retrieve cluster config from peer!
        at net.syncthing.java.bep.ConnectionHandler.connect(ConnectionHandler.kt:172)
        at net.syncthing.java.client.SyncthingClient.openConnection(SyncthingClient.kt:85)
        at net.syncthing.java.client.SyncthingClient.getPeerConnections(SyncthingClient.kt:110)
        at net.syncthing.java.client.SyncthingClient.updateIndexFromPeers(SyncthingClient.kt:125)
        at net.syncthing.java.client.SyncthingClient.access$updateIndexFromPeers(SyncthingClient.kt:38)
        at net.syncthing.java.client.SyncthingClient$1.invoke(SyncthingClient.kt:51)
        at net.syncthing.java.client.SyncthingClient$1.invoke(SyncthingClient.kt:38)
        at net.syncthing.java.client.SyncthingClientKt$sam$Runnable$9543d2f5.run(SyncthingClient.kt)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:273)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by l-jonas** [comment]
This happened when the server did reject the connection attempt -> the IOException is correct in this case
