### ISSUE TITLE
File downloading error handling

### ISSUE THREAD

**Issue by l-jonas** [syncthing/syncthing-lite#56]
```
2018-10-07 15:32:17.174 27712-27784/net.syncthing.lite E/ExecutorService: java.io.IOException: received error response, code = NO_SUCH_FILE
        at net.syncthing.a.c.e.c.a(NetworkUtils.kt:11)
        at net.syncthing.a.a.c.a(BlockPuller.kt:118)
        at net.syncthing.a.a.f$v$1.b(ConnectionHandler.kt:398)
        at net.syncthing.a.a.f$v$1.a(ConnectionHandler.kt:46)
        at net.syncthing.a.c.e.b$b.call(ExecutorUtils.kt:40)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

This results in restarting the App (which should not happen)

**Comment by l-jonas** [comment]
https://github.com/syncthing/syncthing-lite/blob/master/syncthing-core/src/main/kotlin/net/syncthing/java/core/utils/ExecutorUtils.kt#L43 is the cause
