### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Bruceforce** [syncthing/syncthing-lite#89]
The App is crashing at startup on my Galaxy S7 with Android 8.0.0. 
I checked that 
* "normal" syncthing is not running
* the device was not connected to the other side, when starting syncthing lite

Does this logcat help? https://gist.github.com/Bruceforce/92c1ad474d68540270c7859d5cc05bcf

**Comment by l-jonas** [comment]
Please filter it by "grep syncthing" or something like that next time, there is much unrelated stuff from other components.

```
11-10 12:53:15.636 18368 18439 E ExecutorService: java.io.IOException: connection ConnectionHandler{address=DeviceAddress(deviceId=GUUMLVD-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX, instanceId=7518497776069011617, address=tcp://192.168.0.75:22000, producer=LOCAL_DISCOVERY, score=7, lastModified=Sat Nov 10 12:53:07 GMT+01:00 2018), lastActive=0.002secs ago} closed
11-10 12:53:15.636 18368 18439 E ExecutorService:  at net.syncthing.a.c.e.c.a(NetworkUtils.kt:11)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at net.syncthing.a.a.g.j(ConnectionHandler.kt:78)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at net.syncthing.a.a.g.a(ConnectionHandler.kt:299)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at net.syncthing.a.a.g.b(ConnectionHandler.kt:199)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at net.syncthing.a.a.g.d(ConnectionHandler.kt:181)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at net.syncthing.a.b.a.a(SyncthingClient.kt:93)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at net.syncthing.a.b.a.a(SyncthingClient.kt:39)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at net.syncthing.a.b.a$f.a(SyncthingClient.kt:83)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at net.syncthing.a.b.a$f.a(SyncthingClient.kt:39)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at net.syncthing.a.a.g$v$1.b(ConnectionHandler.kt:432)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at net.syncthing.a.a.g$v$1.a(ConnectionHandler.kt:48)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at net.syncthing.a.c.e.b$b.call(ExecutorUtils.kt:40)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11-10 12:53:15.636 18368 18439 E ExecutorService:  at java.lang.Thread.run(Thread.java:764)
```

The error handling is not good currently (a wrong behaving other side can simply crash the App). Which App version did you use (to make the line numbers usable)?

**Comment by Bruceforce** [comment]
Okay sorry, I'll filter it next time. Didn't want to cut anything useful this time.

I'm using app version 0.3.2 from play store.

**Comment by l-jonas** [comment]
Is this only sometimes or does it occur always? The problem here is that the connection is closed after the cluster config was received but before the index messages were sent.

There is a rework of this part of the App currently (waiting for the review), so I would not try to fix anything here if it only occurs sometimes (If it happens with the new code, then it's of course differently).

**Comment by Bruceforce** [comment]
It occurs always. I tried to delete index and cache but this didn't help as well.

I'll check back when the new code is merged and the app is released.

**Comment by l-jonas** [comment]
It shouldn't occur always. That's eventually even a problem of the new implementation, so it's better to understand it. Could you create a new log with a "stable" setup? The existing log contains connecting to 2 devices, but not all log entries contain the device id. So it would be better to remove one device/ disable syncthing at all devices except one. And then it's important if there is only one folder from that device or multiple ones (the second case could problems with the current code, but I'm not sure about it).

**Comment by Bruceforce** [comment]
Okay

1. I cleared app data so that I got a new ID on my S7
1. I stopped other syncthing instances in my LAN (besides S7 and srv)
1. I shared only one folder from srv with S7
1. The app crashed after a few minutes
1. I restarted the app and it crashed again after a few seconds this time

I filtered the log by "syncthing" this time. I hope this is okay. https://gist.github.com/Bruceforce/51b64d549b30b630b757becd99244782

**Comment by l-jonas** [comment]
@Bruceforce The filtering is OK. This time it's an other problem for which I created <https://github.com/syncthing/syncthing-lite/issues/90>. Please read my idea to analyze it further there.

**Comment by l-jonas** [comment]
@Bruceforce I think that this is fixed now. Is it?

**Comment by Bruceforce** [comment]
@l-jonas yes, I think it is. Thanks.
