### ISSUE TITLE
FilenameUtils.normalizeNoEndSeparator(path, true) must not be null

### ISSUE THREAD

**Issue by l-jonas** [syncthing/syncthing-lite#90]
App version: 0.3.2.

```
11-10 19:36:39.345  1389  1571 E ExecutorService: java.lang.IllegalStateException: FilenameUtils.normalizeNoEndSeparator(path, true) must not be null
11-10 19:36:39.345  1389  1571 E ExecutorService:  at net.syncthing.a.c.e.d.e(PathUtils.kt:25)
11-10 19:36:39.345  1389  1571 E ExecutorService:  at net.syncthing.a.c.e.d.c(PathUtils.kt:38)
11-10 19:36:39.345  1389  1571 E ExecutorService:  at net.syncthing.a.c.a.f.<init>(FileInfo.kt:41)
11-10 19:36:39.345  1389  1571 E ExecutorService:  at net.syncthing.a.c.a.f$a.d(FileInfo.kt:163)
11-10 19:36:39.345  1389  1571 E ExecutorService:  at net.syncthing.a.a.k.a(IndexHandler.kt:169)
11-10 19:36:39.345  1389  1571 E ExecutorService:  at net.syncthing.a.a.k$b$a.a(IndexHandler.kt:407)
11-10 19:36:39.345  1389  1571 E ExecutorService:  at net.syncthing.a.a.k$b$b.a(IndexHandler.kt:330)
11-10 19:36:39.345  1389  1571 E ExecutorService:  at net.syncthing.a.a.k$b$a.run(IndexHandler.kt:357)
11-10 19:36:39.345  1389  1571 E ExecutorService:  at net.syncthing.a.c.e.b$a.b(ExecutorUtils.kt:31)
11-10 19:36:39.345  1389  1571 E ExecutorService:  at net.syncthing.a.c.e.b$a.a(Unknown Source:0)
11-10 19:36:39.345  1389  1571 E ExecutorService:  at net.syncthing.a.c.e.b$b.call(ExecutorUtils.kt:40)
11-10 19:36:39.345  1389  1571 E ExecutorService:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-10 19:36:39.345  1389  1571 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-10 19:36:39.345  1389  1571 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11-10 19:36:39.345 1389 1571 E ExecutorService: at java.lang.Thread.run(Thread.java:764)
```
> I cleared app data so that I got a new ID on my S7
> I stopped other syncthing instances in my LAN (besides S7 and srv)
> I shared only one folder from srv with S7
> The app crashed after a few minutes
> I restarted the app and it crashed again after a few seconds this time

(from <https://github.com/syncthing/syncthing-lite/issues/89>)

Could you do this again with <https://github.com/syncthing/syncthing-lite/commit/60d873b7cd10abf4b48d03f773d61528fff904b6> applied? Or, to isolate it more, does it occur if you create a new folder, put a few test files in it and share this new folder.

**Comment by Bruceforce** [comment]
@l-jonas ah sorry. I left the "net.syncthing" filter on, but there was no "net.syncthing" in that line. Do you just need the one line with PathUtils before the crash or all other lines with PathUtils before the crash too? Here is the line right above the crash - otherwise I'd have to replace some stuff.

`11-11 20:41:45.698 10456 10543 W PathUtils: PathUtils.normalizePath: ~$Brief.dot/..`

**Comment by l-jonas** [comment]
This line is enough. I could reproduce the bug by creating a file called ```~Test.txt```

**Comment by l-jonas** [comment]
@Bruceforce Could you please test if the referenced pull request solves this crash for you (it works for me)?

**Comment by Bruceforce** [comment]
@l-jonas thanks for the fix! The one previous with "~" seems to work no. But it crashes again with:

```
11-13 01:55:34.332  3174  3403 V IndexHandler: discarding record = FileRecord{folder=id-here, path=Some Folder/XX_Xxxxxx-Xx_Xxx_Xxxx-(xxxxxx)-1234-X4, size=null, lastModified=Fri Jan 15 01:05:15 GMT+01:00 2016, type=DIRECTORY, last version = Version{id=3830528999313350446, value=1}}, modified before local record
11-13 01:55:34.333  3174  3403 E ExecutorService: java.lang.IllegalArgumentException: provided path is invalid
11-13 01:55:34.333  3174  3403 E ExecutorService:  at net.syncthing.java.core.utils.PathUtils.assertPathValid(PathUtils.kt:45)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at net.syncthing.java.core.utils.PathUtils.getFileName(PathUtils.kt:79)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at net.syncthing.java.core.beans.FileInfo.<init>(FileInfo.kt:40)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at net.syncthing.java.core.beans.FileInfo$Builder.build(FileInfo.kt:163)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at net.syncthing.java.bep.IndexHandler.pushRecord(IndexHandler.kt:168)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at net.syncthing.java.bep.IndexHandler$IndexMessageProcessor$ProcessingRunnable.doHandleIndexMessageReceivedEvent(IndexHandler.kt:406)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at net.syncthing.java.bep.IndexHandler$IndexMessageProcessor$ProcessingRunnable.doHandleIndexMessageReceivedEvent(IndexHandler.kt:377)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at net.syncthing.java.bep.IndexHandler$IndexMessageProcessor$storeAndProcessBg$1.runProcess(IndexHandler.kt:342)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at net.syncthing.java.bep.IndexHandler$IndexMessageProcessor$ProcessingRunnable.run(IndexHandler.kt:356)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at net.syncthing.java.core.utils.ExecutorUtilsKt$submitLogging$1.invoke(ExecutorUtils.kt:31)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at net.syncthing.java.core.utils.ExecutorUtilsKt$submitLogging$1.invoke(Unknown Source:0)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at net.syncthing.java.core.utils.ExecutorUtilsKt$submitLogging$2.call(ExecutorUtils.kt:40)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11-13 01:55:34.333  3174  3403 E ExecutorService:  at java.lang.Thread.run(Thread.java:764)
```

**Comment by l-jonas** [comment]
@Bruceforce The message from the discarded record is triggered when the FileInfo is already created (but the exception is thrown during creating it) -> The log does not offer the required details. Please do it again with <https://github.com/syncthing/syncthing-lite/commit/46bef2e85149497148649fa83c96ce819e74223f>.

**Comment by Bruceforce** [comment]
@l-jonas sorry for the late reply, I was very busy the last few days.

`11-17 02:06:38.348  2946  3017 E ExecutorService: java.lang.IllegalArgumentException: provided path XX Xxxxxx/Xxxxxxxx..._Xxx_Xxxxx is invalid`

**Comment by l-jonas** [comment]
@Bruceforce To make sure that I read it correctly: Are the "..." part of the path or is it just a placeholder for a long string?

**Comment by Bruceforce** [comment]
Only placeholder are X and x. So "..." is part of the folder name.

**Comment by l-jonas** [comment]
@Bruceforce The ".." was a problem (even if it was only somewhere and not a single element). This should be fixed with <https://github.com/syncthing/syncthing-lite/commit/c9f3c487197910fa2ad8a35c3cf814dcdcb35e3b> (this is the version with the more detailed error logging in case there is more)

**Comment by Bruceforce** [comment]
@l-jonas this seems to fix all my awkward file and folder name issues. However the app crashed sometimes while loading the index and I had to restart it. After a few restarts it completed the download of the index. The error was

```
11-18 01:20:16.068 25041 26050 E ExecutorService: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@dc58468 rejected from java.util.concurrent.ThreadPoolExecutor@be14081[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 291]
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:633)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.core.utils.ExecutorUtilsKt.submitLogging(ExecutorUtils.kt:38)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.core.utils.ExecutorUtilsKt.submitLogging(ExecutorUtils.kt:31)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.bep.IndexHandler$IndexMessageProcessor.processBg(IndexHandler.kt:327)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.bep.IndexHandler$IndexMessageProcessor.handleIndexMessageReceivedEvent(IndexHandler.kt:319)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.bep.IndexHandler.handleIndexMessageReceivedEvent(IndexHandler.kt:141)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.bep.ConnectionHandler$startMessageListenerService$1$1.invoke(ConnectionHandler.kt:396)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.bep.ConnectionHandler$startMessageListenerService$1$1.invoke(ConnectionHandler.kt:48)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.core.utils.ExecutorUtilsKt$submitLogging$2.call(ExecutorUtils.kt:40)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.lang.Thread.run(Thread.java:764)
```

**Comment by l-jonas** [comment]
I created a new issue for the new error.
