### ISSUE TITLE
RejectedExecutionException at IndexHandler

### ISSUE THREAD

**Issue by l-jonas** [syncthing/syncthing-lite#94]
```
11-18 01:20:16.068 25041 26050 E ExecutorService: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@dc58468 rejected from java.util.concurrent.ThreadPoolExecutor@be14081[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 291]
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:633)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.core.utils.ExecutorUtilsKt.submitLogging(ExecutorUtils.kt:38)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.core.utils.ExecutorUtilsKt.submitLogging(ExecutorUtils.kt:31)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.bep.IndexHandler$IndexMessageProcessor.processBg(IndexHandler.kt:327)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.bep.IndexHandler$IndexMessageProcessor.handleIndexMessageReceivedEvent(IndexHandler.kt:319)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.bep.IndexHandler.handleIndexMessageReceivedEvent(IndexHandler.kt:141)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.bep.ConnectionHandler$startMessageListenerService$1$1.invoke(ConnectionHandler.kt:396)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.bep.ConnectionHandler$startMessageListenerService$1$1.invoke(ConnectionHandler.kt:48)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at net.syncthing.java.core.utils.ExecutorUtilsKt$submitLogging$2.call(ExecutorUtils.kt:40)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
11-18 01:20:16.068 25041 26050 E ExecutorService:  at java.lang.Thread.run(Thread.java:764)
```

(from <https://github.com/syncthing/syncthing-lite/issues/90#issuecomment-439658378>)

This looks like a index message arrived after after the shut down of the SyncthingClient. 

@Bruceforce Theoretically, this occurs if you close/ leave Syncthing Lite while the index was not received fully. Was it this way in your case?

If it is what I think, then there are 2 solutions:

- don't shutdown the index change executor or
- ignore it (the other client would theoretically send it again because the sequence number at Syncthing Lite was not updated in this case)

I would use the second one.

**Comment by Bruceforce** [comment]
@l-jonas I shared a few bigger folders (+ 2TB in total) and let syncthing lite open in foreground. A few minutes after the screen of my phone went off, syncthing lite seemed to be disconnected from the server. What do you mean by "ignore it"? Just starting the syncthing lite client over again till it completes?

**Comment by l-jonas** [comment]
@Bruceforce It should disconnect 60 seconds after it was closed or the screen was turned off. And that's when this occurs theoretically (due to the shutdown of the client). "Ignore it" means to catch it within Syncthing Lite so that it does not cause a crash. For the index update in the background: I created <https://github.com/syncthing/syncthing-lite/issues/95>
